Repository engineerjoe440/pycev, pull requests merged in 2022-09, with the labels that each got.

#11 reduced functional breakout to lower call-cost
  pycev/pycev.py
Labels: enhancement

#12 Release of v0.1.0
  .github/workflows/release.yml
  .gitignore
  README.md
  docsource/conf.py
  docsource/index.rst
  docsource/sphinxrequires.txt
  pycev/pycev.py
  release-version.py
  tests/functional/test_loadcev.py
  tests/functional/test_loadeverycev.py
  tests/unit/test_checksum.py
  tests/unit/test_importpycev.py
Labels: bug, documentation, enhancement

#13 corrected release plan
  .github/workflows/release.yml
Labels: bug, ci

#14 corrected release plan
  .github/workflows/release.yml
Labels: bug, ci

#17 Moved pycev.py to the root directory
  pycev.py
  pycev/__init__.py
  setup.py
  tests/unit/test_importpycev.py
Labels: enhancement
